### ISSUE TITLE
onPause causes app crashes on Android

### ISSUE THREAD

**Issue by SalSchein** [cordova-plugin-facebook-connect/cordova-plugin-facebook-connect#128]
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ripalip, PID: 31518
    java.lang.NoSuchMethodError: No static method deactivateApp(Landroid/content/Context;)V in class Lcom/facebook/appevents/AppEventsLogger; or its super classes (declaration of 'com.facebook.appevents.AppEventsLogger' appears in /data/app/com.ripalip-MYsHnWy5O4npfJjFv27lQg==/base.apk)
        at org.apache.cordova.facebook.ConnectPlugin.onPause(ConnectPlugin.java:257)
        at org.apache.cordova.PluginManager.onPause(PluginManager.java:211)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.handlePause(MockCordovaWebViewImpl.java:132)
        at com.getcapacitor.Bridge.onPause(Bridge.java:1094)
        at com.getcapacitor.BridgeActivity.onPause(BridgeActivity.java:136)
        at android.app.Activity.performPause(Activity.java:7451)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1414)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4115)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4092)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4066)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4040)
        at android.app.ActivityThread.-wrap16(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by SalSchein** [comment]
I could fix this plugin crash error in MainActivity.


public class MainActivity extends BridgeActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            public void uncaughtException(Thread paramThread, Throwable paramThrowable) {
                Log.e("Error"+Thread.currentThread().getStackTrace()[2],paramThrowable.getLocalizedMessage());
            }
        });
    }
}
